
# !/bin/bash

set -x

# rm -rf *

# -DCMAKE_C_COMPILER_LAUNCHER=ccache
# -DCMAKE_CXX_COMPILER_LAUNCHER=ccache


cmake \
   ../../llvm \
  -DCMAKE_CXX_FLAGS="-ggdb -gline-tables-only" \
  -DLLVM_TARGETS_TO_BUILD="X86" \
  -DCMAKE_BUILD_TYPE=Debug \
  -DBUILD_SHARED_LIBS=ON \
  -DLLVM_USE_SPLIT_DWARF=ON \
  -DLLVM_BUILD_EXAMPLES=ON \
  -DLLVM_BUILD_TESTS=ON \
  -GNinja $1

#-DCMAKE_CXX_FLAGS="-Wpadded"
#-DLLVM_USE_SPLIT_DWARF=ON
#-DLLVM_PARALLEL_LINK_JOBS=2
#-DLLVM_PARALLEL_COMPILE_JOBS=6
#-DLLVM_APPEND_VC_REV=OFF
#-DLLVM_TARGETS_TO_BUILD="X86"

#-DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_LINK_LLVM_DYLIB=ON

#-DLLVM_ENABLE_ASSERTIONS=OFF
#-DLLVM_FORCE_ENABLE_DUMP=OFF
#-DLIBCXX_ENABLE_ASSERTIONS=OFF
#-DLIBCXXABI_ENABLE_ASSERTIONS=OFF
#-DBUILD_SHARED_LIBS=ON
