# !/bin/bash

set -x

# rm -rf *

# -DCMAKE_C_COMPILER_LAUNCHER=ccache
# -DCMAKE_CXX_COMPILER_LAUNCHER=ccache


cmake ../../llvm \
-DCMAKE_BUILD_TYPE=Debug \
-DLLVM_TARGETS_TO_BUILD="X86" \
-DBUILD_SHARED_LIBS=ON \
-DLLVM_PARALLEL_LINK_JOBS=2 \
-DLLVM_APPEND_VC_REV=OFF \
-GNinja $1

#-DLLVM_PARALLEL_COMPILE_JOBS=6
